[package]
name = "pdf-pwbf"
version = "0.1.0"
edition = "2024"

[dependencies]
lopdf = "0.38.0"
clap = { version = "4.5", features = ["derive"] }
indicatif = "0.17"
rayon = "1.10"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
